apiVersion: v1
kind: Service
metadata:
  name: leenustechs-lightroomapi-service
  namespace: default
  labels:
    app: leenustechs-lightroomapi-service
spec:
  type: NodePort
  selector:
    app: leenustechs-lightroomapi-service
  ports:
    - protocol: TCP
      port: 8085        # Puerto interno del servicio
      targetPort: 8085  # Puerto del contenedor
      nodePort: 30085   # Puerto que estará expuesto en los nodos (30000-32767)